### ISSUE TITLE
Update Service id pickup for pickup_availability request.

### ISSUE THREAD

**Issue by DevilalDheer** [jazminschroeder/fedex#101]
Hi Team,

When I execute this:

 fedex.pickup_availability(:country_code => 'IN',
                                   :postal_code => '400061',
                                   :request_type => 'FUTURE_DAY',
                                   :dispatch_date => dispatch_date,
                                   :carrier_code => 'FDXE')

I got error: 
Fedex::RateError
{"Fault"=>{"faultcode"=>"soapenv:Server", "faultstring"=>"Schema validation failed for request.", "detail"=>{"fault"=>{"errorCode"=>"5", "reason"=>"Schema validation failed for request.", "details"=>{"ValidationFailureDetail"=>{"message"=>"string value 'pickup' is not a valid enumeration value for ServiceIdType in namespace http://fedex.com/ws/pickup/v5", "xmlLocation"=>{"ServiceId"=>"pickup"}}}}}}}

Need to change service_id 'pickup' to 'disp'

PR for this:
https://github.com/jazminschroeder/fedex/pull/95/files

Thanks

**Comment by jazminschroeder** [comment]
Yes, looks like the recent version of pick up api is using `disp`. The PR has been merged and a new gem version was released(3.9.x)
