### ISSUE TITLE
CustomerReference

### ISSUE THREAD

**Issue by ghost** [jazminschroeder/fedex#65]
I am having a hell of a time using the CustomerReference options to generate the "Ref:" line on the fedex label.

currently i am trying this:

def customer_references s
    {
      type: 'CUSTOMER_REFERENCE',
      value: "#{s.key} - #{s.li_model.upcase || ''}"
    }
  end

packages << {
          weight: { units: 'LB', value: weight },
          customer_references: customer_references(s),
          dimensions: { units: 'IN', length: length, width: width, height: height }
        }

and am getting the error: 
"customerReference value is invalid for customer reference 2 in requestedPackage 1"

I see no test coverage for customer reference support.  Does anyone have any recent experience in trying to do such a thing?

I'm just asking incase someone has some insight for me before I dig deeper and fork the gem to add/fix such functionality.

**Comment by Metuz** [comment]
And what about INVOICE_NUMBER and P_O_NUMBER in customer_references?

**Comment by reymon29** [comment]
> And what about INVOICE_NUMBER and P_O_NUMBER in customer_references?

Hope this helps but looking at the documentation and with no luck, finally coming across an old past issue back in 2013 @bradediger is the best! Where you need to pass the additional fields as a new hash within an array like this.

Shipping.label(
  format: 'pdf',
  filename: 'label.pdf',
  # ...
  packages: [
    {
      weight: {value: 1, units: 'LB'},
      customer_references: [
        "Order #12345", # default is CUSTOMER_REFERENCE
        {type: 'RMA_ASSOCIATION', value: 'RA_2468'} # custom type
      ]
    }
  ]
)

https://github.com/jazminschroeder/fedex/pull/31
