### ISSUE TITLE
How do we get different SERVICE_TYPES and how do we use it.

### ISSUE THREAD

**Issue by AnujDubey** [jazminschroeder/fedex#77]
In my application Fedex::Shipment::SERVICE_TYPES::GROUND_HOME_DELIVERY is giving error that uninitialize constant "Fedex::Shipment". How to use it and what are the different types of service types. Please help.

**Comment by jazminschroeder** [comment]
To get a list of all available services types: ```Fedex::Request::Base::SERVICE_TYPES```. Some of the API's such as fedex rate would take the service type as part of the request hash. Please refer to the README for more information.
