### ISSUE TITLE
Transit time estimation actually generates a shipment and label.

### ISSUE THREAD

**Issue by ELouisYoung** [jazminschroeder/fedex#88]
According to fedex if you do as your example shows:

ship = fedex.ship(:shipper=>shipper,
                  :recipient => recipient,
                  :packages => packages,
                  :service_type => "FEDEX_GROUND",
                  :shipping_options => shipping_options)
puts ship[:completed_shipment_detail][:operational_detail] [:transit_time]

This will actually generate a shipment on your account that fedex will be expecting to pick up.
I'm working on this in my own fork of the gem, and I post an update here when done.

**Comment by jazminschroeder** [comment]
I am so sorry to hear. I have updated the README. Will look into incorporating the changes from your code. Thank you!!
