### ISSUE TITLE
How to get expected arrival time in fedex rate() ?

### ISSUE THREAD

**Issue by Debadatta** [jazminschroeder/fedex#89]
Currently we can not get the expected arrival time/transit time in fedex.rate() method . 
It does not show for all service types, but it shows for only FEDEX_GROUND and GROUND_HOME_DELIVERY . 

If we go through the fedex site and make a quote it returns the transit time . Please look into this . If there is any other method and not listed in the readme file, please update .

**Comment by jazminschroeder** [comment]
I have noticed this. Time/transit is not populated for all service types, that is the API response fedex provides. Please keep in mind the fedex website may not be using the same API they expose to the public.  If you could do some research on your own or check w Fedex webservices team and share with us what you find it would be greatly appreciated! Thanks!!
