### ISSUE TITLE
Can we get 2 types of labels from fedex API?

### ISSUE THREAD

**Issue by Debadatta** [jazminschroeder/fedex#90]
Can we get 2 types of labels from fedex API?

We can get one label in either .pdf or .pcx format . How can we get both types of label in single label request ?

Currently the thermal printer generating by passing image_type => "EPL2"

example_spec = {
  :image_type => "EPL2",
  :label_stock_type => "STOCK_4X6"
}

label = fedex.label(:filename => "my_dir/example_epl2.pcx",
                    :shipper=>shipper,
                    :recipient => recipient,
                    :packages => packages,
                    :service_type => "FEDEX_GROUND",
                    :shipping_options => shipping_options,
                    :label_specification => example_spec)

The file saved in .pcx format . But the file could not open in any tool . Tried to open in linux but it says invalid pcx file .

**Comment by jazminschroeder** [comment]
Not supported in this gem. Not sure if the Fedex API has the ability to do it. Please refer to the Fedex documentation. Thank you!
