### ISSUE TITLE
How to set rate_request_type => 'RETAIL'

### ISSUE THREAD

**Issue by rajeshlmindfiresolutions** [jazminschroeder/fedex#98]
How to set rate_request_type => 'RETAIL' 

We need the exact results from fedex . We checked in base.rb the rate_request_type is set to 'ACCOUNT', We checked by changing rate_request_type => 'RETAIL'  , but it is sending the same result . And it is very diffrent than what fedex is showing .

**Comment by jazminschroeder** [comment]
Sorry, I am not familiar with this option. Fedex continuously add functionality to new versions of the API. Please check the Fedex documentation. If you find a solution and want to contribute PR's are always welcome!
